 [libdefaults]
   default_realm = EXAMPLE.COM
   dns_lookup_realm = false
   dns_lookup_kdc = false
   rdns = false
   forwardable = true

 [realms]
   EXAMPLE.COM = {
     kdc = dc01.example.com
     kdc = dc02.example.com
     admin_server = dc01.example.com
   }

 [domain_realm]
   .example.com = EXAMPLE.COM
   example.com = EXAMPLE.COM
